Repository spinnaker/clouddriver, pull requests merged in 2020-10, with the labels that each got.

#4965 feat(exceptions): Process validation errors with ExceptionMessageDecorator prior to throwing DescriptionValidationException
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/DeployConfiguration.groovy
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionAuthorizer.java
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/deploy/DescriptionValidationException.java
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsService.java
  clouddriver-core/src/test/groovy/com/netflix/spinnaker/clouddriver/orchestration/OperationsServiceSpec.groovy
Labels: ready to merge

#4966 fix(aws): Dont override imdsv2 flag when cloning LT backed asg
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/CopyLastAsgAtomicOperation.groovy
Labels: ready to merge

#4970 fix (aws/lambda) : Send back results from invoke lambda atomic operation
  clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/description/InvokeLambdaFunctionOutputDescription.java
  clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/deploy/ops/InvokeLambdaAtomicOperation.java
Labels: auto merged, ready to merge

#4967 fix(provider/cf): only perform ondemand caching when account equals the credentials account
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgent.java
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryLoadBalancerCachingAgentTest.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgentTest.java
Labels: auto merged, ready to merge

#4971 test(aws/lambda) : Start a dummy test class for lambda.
  clouddriver-lambda/clouddriver-lambda.gradle
  clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/InvokeLambdaAtomicOperationTest.java
Labels: auto merged, ready to merge

#4862 feat(aws): Support cross zone load balancing for NLB
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerV2Description.java
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerV2UpsertHandler.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperation.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonApplicationLoadBalancerCachingAgent.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerV2AtomicOperationSpec.groovy
Labels: auto merged, ready to merge

#4977 refactor(aws): Updating launch template rollout flag
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorker.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/AutoScalingWorkerUnitSpec.groovy
Labels: ready to merge

#4978 chore(kotlin): use the JDK 11 kotlin libs
  gradle/kotlin-test.gradle
Labels: ready to merge

#4949 fix(Oracle): Fixed version support for deploying artifacts from Oracle object storage
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/oracle/OracleArtifactCredentials.java
Labels: auto merged, ready to merge

#4985 fix(gce): remove the ONLY_DOWN deprecated AutoscalingMode
  clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleAutoscalingPolicy.groovy
  clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgent.java
  clouddriver-google/src/test/groovy/com/netflix/spinnaker/clouddriver/google/provider/agent/AbstractGoogleServerGroupCachingAgentTest.java
Labels: auto merged, ready to merge

#4989 fix(aws): use the Spinnaker region provider with the sts client builder, so that it defaults to the default region, when no region is defined
  build.gradle
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/NetflixSTSAssumeRoleSessionCredentialsProvider.java
Labels: ready to merge

#4991 fix(provider/cf): fix regression caused by clusterSummaries
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepository.java
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/view/CloudFoundryClusterProvider.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java
Labels: auto merged, backport-candidate, ready to merge

#4992 fix(titus): Store application ref for server groups and instances
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
Labels: auto merged, ready to merge

#4993 Revert "fix(titus): Store application ref for server groups and instances"
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
Labels: ready to merge

#4995 chore(kork): update kork dependency (now w/ moniker)
  clouddriver-alicloud/clouddriver-alicloud.gradle
  clouddriver-api/clouddriver-api.gradle
  clouddriver-appengine/clouddriver-appengine.gradle
  clouddriver-aws/clouddriver-aws.gradle
  clouddriver-azure/clouddriver-azure.gradle
  clouddriver-cloudfoundry/clouddriver-cloudfoundry.gradle
  clouddriver-core/clouddriver-core.gradle
  clouddriver-dcos/clouddriver-dcos.gradle
  clouddriver-google/clouddriver-google.gradle
  clouddriver-huaweicloud/clouddriver-huaweicloud.gradle
  clouddriver-kubernetes/clouddriver-kubernetes.gradle
  clouddriver-oracle/clouddriver-oracle.gradle
  clouddriver-tencentcloud/clouddriver-tencentcloud.gradle
  clouddriver-titus/clouddriver-titus.gradle
  clouddriver-web/clouddriver-web.gradle
  gradle.properties
Labels: ready to merge

#4939 chore(codeowners): Add german-muzquiz to kubernetes codeowners
  CODEOWNERS
Labels: auto merged, ready to merge

#4962 feat(clouddriver): Add support for Redis SSL
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfig.groovy
Labels: auto merged, ready to merge

#4938 fix(titus): Update error handling
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/ops/AbstractEnableDisableAtomicOperation.groovy
Labels: auto merged, ready to merge

#5000 feat(azure): Enable Azure from cloud providers
  settings.gradle
Labels: ready to merge

#4998 perf(cats/sql): Introduce V2 SQL cache schema
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/SqlProviderCache.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlAdminCommandsRepository.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNames.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlSchemaVersion.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgent.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/controllers/CatsSqlAdminController.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlCacheConfiguration.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConstraints.kt
  cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlNamesTest.kt
  cats/cats-sql/src/test/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlUnknownAgentCleanupAgentTest.kt
  clouddriver-sql/src/main/resources/db/changelog-master.yml
  clouddriver-sql/src/main/resources/db/changelog/20200709-cats-v2.yml
Labels: auto merged, ready to merge

#4976 feat(aws): update awscli and s3cmd
  Dockerfile.slim
  Dockerfile.ubuntu
Labels: auto merged, ready to merge

#5001 chore(kt): switch back to kotlin-stdlib-jdk8
  gradle/kotlin-test.gradle
Labels: ready to merge

#5003 fix(aws): Fixing NPE while retrieving imageId in launch templates
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonClusterProvider.groovy
Labels: ready to merge

#5009 fix(provider/aws): handle SGs with `:` in the name
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/cache/KeysSpec.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonSecurityGroupProviderSpec.groovy
Labels: auto merged, ready to merge

#5013 fix(aws): Tweaked error message when security group tagging fails
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
Labels: ready to merge

#5005 fix(discovery): Make 404s non fatal for enabling ASG in discovery
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DisableAsgAtomicOperationUnitSpec.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/EnableAsgAtomicOperationUnitSpec.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/discovery/DiscoverySupportUnitSpec.groovy
  clouddriver-eureka/src/main/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupport.groovy
  clouddriver-eureka/src/test/groovy/com/netflix/spinnaker/clouddriver/eureka/deploy/ops/AbstractEurekaSupportSpec.groovy
Labels: auto merged, ready to merge

#5015 chore(*): Adding @ajordens to aws/titus CODEOWNERS
  CODEOWNERS
Labels: auto merged, ready to merge

#5014 Fix (OCI) : Bugfix 5911 Spinnaker - Oracle Load Balancer Regional Subnets don't work
  clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/description/UpsertLoadBalancerDescription.groovy
  clouddriver-oracle/src/main/groovy/com/netflix/spinnaker/clouddriver/oracle/deploy/validator/UpsertLoadBalancerDescriptionValidator.java
Labels: auto merged, ready to merge

#5025 fix(titus): UpsertTitusJobProcesses was missing @Component
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/UpsertTitusJobProcesses.java
Labels: ready to merge

#5017 fix(upgrade): Docker image bump to 3.12 to fix potential JVM error on Git handling
  Dockerfile.slim
Labels: auto merged, ready to merge

#5030 refactor(aws): Refactored LaunchTemplateService
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
Labels: auto merged, ready to merge

#5037 feat(kubernetes): Projected Volume Replacement
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesCronJobHandler.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDaemonSetHandler.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandler.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesJobHandler.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesReplicaSetHandler.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesStatefulSetHandler.java
  clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandlerSpec.groovy
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ReplacerTest.java
Labels: auto merged, ready to merge

#5016 fix(aws): fixed failure to create launch template backed server group with spot instances
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/services/LaunchTemplateService.java
Labels: auto merged, ready to merge

#5050 fix(aws): Restrict the accounts that `LaunchFailureNotificationAgent` runs against
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/lifecycle/LaunchFailureNotificationAgentProvider.java
Labels: ready to merge

#5051 fix(aws lb): Parse LBs with dashes in them
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
Labels: ready to merge

#5044 feat(ecs): Make ECS agents implement AccountAware
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/AbstractEcsCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ScalableTargetsCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/SecretCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceDiscoveryCachingAgent.java
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/provider/config/EcsProviderConfig.java
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/EcsCloudMetricAlarmCachingAgentSpec.groovy
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ScalableTargetCachingAgentSpec.groovy
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/SecretCachingAgentSpec.groovy
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/provider/agent/ServiceDiscoveryCachingAgentSpec.groovy
  clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCacheTest.java
  clouddriver-ecs/src/test/java/com/netflix/spinnaker/clouddriver/ecs/provider/agent/IamRoleCachingAgentTest.java
Labels: auto merged, ready to merge

#5054 chore(aws lbs): Add unit test for AmazonLoadBalancerProvider
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProviderSpec.groovy
Labels: ready to merge

#4876 refactor(aws): Groovy -> Java DeleteAmazonLaunchConfigurationAtomicOp…
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonLaunchConfigurationAtomicOperation.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/DeleteAmazonLaunchConfigurationAtomicOperation.java
Labels: auto merged, ready to merge

#5029 fix(helm): Semver version sorting
  clouddriver-artifacts/clouddriver-artifacts.gradle
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParser.java
  clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/helm/IndexParserTest.java
Labels: auto merged, ready to merge

#5053 feat(aws): added capacityType to instance information cached
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/InstanceCachingAgent.groovy
Labels: auto merged, ready to merge

#5033 fix(cache/aws): Add authoritative type for on demand update
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgent.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ClusterCachingAgentSpec.groovy
Labels: auto merged, ready to merge

#5058 fix(core): Default equals()/hashCode() implementation for `AbstractAccountCredentials`
  clouddriver-security/src/main/groovy/com/netflix/spinnaker/clouddriver/security/AbstractAccountCredentials.java
Labels: auto merged, ready to merge

#5046 chore(kubernetes): bump kubectl binary patch version
  Dockerfile.slim
Labels: auto merged, backport-candidate, ready to merge

#5047 chore(kubernetes): bump kubectl binary minor version
  Dockerfile.slim
Labels: ready to merge

#5042 feat(test): Add integration test cases for ECS CreateServerGroup for task definition inputs and artifacts
  clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/CreateServerGroupSpec.java
  clouddriver-ecs/src/integration/java/com/netflix/spinnaker/clouddriver/ecs/test/CreateServerGroupWithArtifactsSpec.java
  clouddriver-ecs/src/integration/resources/testartifacts/createServerGroup-artifact-EC2-targetGroup-WithNoContainers-artifactFile.json
  clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-inputs-ec2-serviceDiscovery.json
  clouddriver-ecs/src/integration/resources/testoperations/createServerGroup-inputs-ec2-withoutLoadBalacing.json
Labels: auto merged, ready to merge
