Repository spinnaker/clouddriver, pull requests merged in 2020-02, with the labels that each got.

#4301 fix(kubernetes): On refresh, don't replace credentials that have not changed
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/KubernetesV2ProviderSynchronizable.java
Labels: cherry-pick

#4256 feat(provider/tencentcloud): Add initial implementation for TencentCloud provider
  clouddriver-tencentcloud/clouddriver-tencentcloud.gradle
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/TencentCloudOperation.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/TencentCloudProvider.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/cache/Keys.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/config/TencentCloudConfigurationProperties.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/model/TencentCloudBasicResource.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/names/TencentCloudBasicResourceNamer.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudCredentials.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudCredentialsInitializer.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/clouddriver/tencentcloud/security/TencentCloudNamedAccountCredentials.java
  clouddriver-tencentcloud/src/main/java/com/netflix/spinnaker/config/TencentCloudConfiguration.java
  clouddriver-tencentcloud/src/test/java/com/netflix/spinnaker/clouddriver/tencentcloud/cache/KeysTest.java
  settings.gradle
Labels: auto merged, ready to merge

#4227 feat(config/dynamic): Support for local dynamic config files
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/config/CloudFoundryConfiguration.java
  clouddriver-core/clouddriver-core.gradle
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/CloudDriverConfig.groovy
  clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/config/ModifiableFilePropertySources.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesConfiguration.java
Labels: auto merged, ready to merge

#4300 fix(aws): Update diffing logic for AWS upsertSecurityGroupOperation
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupLookupFactory.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy
Labels: auto merged, ready to merge

#4308 fix(titus): Add retry on titus resource_exhausted error
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/SubmitTitusJob.java
Labels: auto merged, ready to merge

#4307 fix(titus): Relax titus security group validation
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/deploy/actions/PrepareTitusDeploy.java
Labels: auto merged, ready to merge

#4309 fix(titus): Attempt to fix circular dependency
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/view/AmazonLoadBalancerProvider.groovy
Labels: auto merged, ready to merge

#4303 refactor(kubernetes): Simplify status handlers
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/Manifest.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/CustomKubernetesHandlerFactory.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesAPIServiceHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleBindingHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesClusterRoleHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesConfigMapHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesControllerRevisionHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesCronJobHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesCustomResourceDefinitionHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesEventHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesIngressHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesLimitRangeHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesMutatingWebhookConfigurationHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesNamespaceHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesNetworkPolicyHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeClaimHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPersistentVolumeHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodDisruptionBudgetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodPresetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodSecurityPolicyHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleBindingHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesRoleHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesSecretHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceAccountHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesServiceHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStorageClassHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesUnregisteredCustomResourceHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesValidatingWebhookConfigurationHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/UnstableReason.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandlerTest.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandlerTest.java
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/deployment/progress-deadline-exceeded-unavailable.yml
Labels: auto merged, ready to merge

#4313 fix(kubernetes): Move generation checks to be object-specific
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/description/manifest/KubernetesManifest.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/model/Manifest.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesCronJobHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesJobHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesReplicaSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandler.java
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/UnstableReason.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDaemonSetHandlerTest.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesDeploymentHandlerTest.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesPodHandlerTest.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesStatefulSetHandlerTest.java
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/statefulset/partitioned-rollout-complete.yml
Labels: auto merged, ready to merge

#4312 chore(build): Generate config manifest
  build.gradle
Labels: auto merged, ready to merge

#4304 chore(ecs): remove attach_pid file
  clouddriver-ecs/.attach_pid7267
Labels: auto merged, ready to merge

#4321 fix(ecs): ECS handling of IAM Roles with a path
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
Labels: auto merged, ready to merge

#4216 feat(huaweicloud): implement cache agent of security group
  clouddriver-huaweicloud/clouddriver-huaweicloud.gradle
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/HuaweiCloudUtils.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/exception/HuaweiCloudException.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroup.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroupCacheData.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSecurityGroupSummary.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/AbstractHuaweiCloudCachingAgent.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/AbstractOnDemandCachingAgent.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSecurityGroupCachingAgent.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSecurityGroupProvider.java
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSecurityGroupCachingAgentSpec.groovy
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSecurityGroupProviderSpec.groovy
Labels: auto merged, ready to merge

#4314 fix(misc): Remove unused bean instance from autowiring
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/providers/TitusTargetGroupServerGroupProvider.java
Labels: auto merged, ready to merge

#4181 feat(aws): Adding support for session stickiness for clbs upsert op
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/description/UpsertAmazonLoadBalancerClassicDescription.java
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy
Labels: ready to merge

#4327 fix(titus): Update filters for observeJob
  clouddriver-titus/src/main/groovy/com/netflix/spinnaker/clouddriver/titus/caching/agents/TitusStreamingUpdateAgent.java
Labels: auto merged, ready to merge

#4337 fix(ecs): Add null check for empty serviceDiscoveryAssociation
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/validators/EcsCreateServerGroupDescriptionValidator.java
Labels: ready to merge

#4346 fix(artifacts): Close OkHttpClient on failures
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/BaseHttpArtifactCredentials.java
Labels: ready to merge

#4349 fix(ecs): only add service role to create request if there is one lb
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
Labels: ready to merge

#4343 fix(aws): Fixing CLBs listener policies getting dropped on upsert
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/handlers/LoadBalancerUpsertHandler.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerAtomicOperation.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/loadbalancer/UpsertAmazonLoadBalancerClassicAtomicOperationSpec.groovy
Labels: auto merged, ready to merge

#4336 chore(reservations): Disable reservation reports by default
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
Labels: auto merged, ready to merge

#4345 fix(docker/test): Switch to java.util.Base64
  clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy
Labels: auto merged, ready to merge

#4353 chore(gcb build): add a .gcloudignore
  .gcloudignore
Labels: ready to merge

#4355 fix(aws): add .get() to optional known to be present
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/config/AwsProviderConfig.groovy
Labels: ready to merge

#4330 feat(huaweicloud): implement cache agent of network
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/CacheResultBuilder.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudNetwork.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/HuaweiCloudInfrastructureProvider.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudNetworkCachingAgent.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/config/HuaweiCloudInfrastructureProviderConfig.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudNetworkProvider.java
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudNetworkCachingAgentSpec.groovy
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudNetworkProviderSpec.groovy
Labels: auto merged, ready to merge

#4333 chore(plugins): adding plugins dir and application name
  Dockerfile.slim
  Dockerfile.ubuntu
  Dockerfile.ubuntu-java8
Labels: auto merged, ready to merge

#4356 fix(aws): Handle SG upsert with description object already present in console
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/SecurityGroupIngressConverter.groovy
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperation.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/securitygroup/UpsertSecurityGroupAtomicOperationUnitSpec.groovy
Labels: auto merged, ready to merge

#4357 fix(kubernetes): Fix spaces in error message on artifact bind failure
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/manifest/KubernetesDeployManifestOperation.java
Labels: auto merged, ready to merge

#4358 feat(kubernetes): prepare for upcoming removal of V1 provider
  clouddriver-kubernetes-v1/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/security/KubernetesV1Credentials.java
  clouddriver-kubernetes-v1/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v1/provider/KubernetesV1ProviderSynchronizableSpec.groovy
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
Labels: auto merged, ready to merge

#4363 feat(kube): add stability check for HPA kind
  clouddriver-kubernetes-v2/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerHandler.java
  clouddriver-kubernetes-v2/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/KubernetesHorizontalPodAutoscalerTest.java
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/horizontalpodautoscaler/base.yml
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/horizontalpodautoscaler/no-replicas.yml
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/horizontalpodautoscaler/stable.yml
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/horizontalpodautoscaler/waiting-for-scaledown.yml
  clouddriver-kubernetes-v2/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/v2/op/handler/horizontalpodautoscaler/waiting-for-scaleup.yml
Labels: auto merged, ready to merge

#4364 feat(huaweicloud): implement cache agent of subnet
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/cache/Keys.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClient.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/client/HuaweiCloudClientImpl.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/model/HuaweiCloudSubnet.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/HuaweiCloudInfrastructureProvider.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSubnetCachingAgent.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/config/HuaweiCloudInfrastructureProviderConfig.java
  clouddriver-huaweicloud/src/main/java/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSubnetProvider.java
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/agent/HuaweiCloudSubnetCachingAgentSpec.groovy
  clouddriver-huaweicloud/src/test/groovy/com/netflix/spinnaker/clouddriver/huaweicloud/provider/view/HuaweiCloudSubnetProviderSpec.groovy
Labels: auto merged, ready to merge

#4323 fix(ecs): ECS IAM Path role fix for 1.17
  clouddriver-ecs/src/main/java/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperation.java
  clouddriver-ecs/src/test/groovy/com/netflix/spinnaker/clouddriver/ecs/deploy/ops/CreateServerGroupAtomicOperationSpec.groovy
Labels: auto merged, ready to merge

#4365 feat(alicloud): Add findImage and ScalingActivitie Controller
  clouddriver-alicloud/clouddriver-alicloud.gradle
  clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/controllers/AliCloudImageController.java
  clouddriver-alicloud/src/main/java/com/netflix/spinnaker/clouddriver/alicloud/controllers/AliCloudScalingActivitiesController.java
  clouddriver-alicloud/src/test/java/com/netflix/spinnaker/clouddriver/alicloud/controllers/AliCloudImageControllerTest.java
  clouddriver-alicloud/src/test/java/com/netflix/spinnaker/clouddriver/alicloud/controllers/AliCloudScalingActivitiesControllerTest.java
Labels: auto merged, ready to merge

#4306 fix(dockerfiles/google): Add in the Google Cloud SDK Appengine Go plugins.
  Dockerfile.java8
  Dockerfile.slim
  Dockerfile.ubuntu
  Dockerfile.ubuntu-java8
Labels: auto merged, ready to merge
