Repository spinnaker/clouddriver, pull requests merged in 2021-12, with the labels that each got.

#5586 fix(elasticsearch): Unpinning elasticsearch package and removing deprecated Elasticsearch transport and Jest library
  clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
  clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy
Labels: ready to merge

#5588 fix(jobs): Update account permission check to check for WRITE instead
  clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy
Labels: ready to merge

#5589 fix(clouddriver-sql): add missing com.fasterxml.jackson.core:jackson-annotations and com.fasterxml.jackson.core:jackson-databind dependencies
  clouddriver-sql/clouddriver-sql.gradle
Labels: ready to merge

#5577 fix(cloudfoundry): skip API calls for apps that won't be cached
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Applications.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ApplicationsTest.java
Labels: ready to merge, auto merged, backport-candidate

#5219 chore(build): gradle 6.8.1
  gradle/wrapper/gradle-wrapper.properties
Labels: ready to merge, auto merged

#5461 fix(aws): Generate Valid Scaling Policy Name
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopier.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/scalingpolicy/DefaultScalingPolicyCopierSpec.groovy
Labels: ready to merge, auto merged

#5593 feat(docker): migrate to kork-credentials
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/CloneCloudFoundryServerGroupAtomicOperationConverter.java
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
  clouddriver-docker/clouddriver-docker.gradle
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/config/DockerRegistryConfigurationProperties.groovy
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/DockerRegistryProvider.groovy
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/config/DockerRegistryProviderConfig.groovy
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
  clouddriver-docker/src/main/groovy/com/netflix/spinnaker/config/DockerRegistryConfiguration.groovy
  clouddriver-docker/src/main/java/com/netflix/spinnaker/clouddriver/docker/registry/health/DockerRegistryHealthIndicator.java
  clouddriver-docker/src/main/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsLifecycleHandler.java
  clouddriver-docker/src/main/java/com/netflix/spinnaker/config/DockerDefaultConfiguration.java
  clouddriver-docker/src/main/java/com/netflix/spinnaker/config/DockerRegistryConfiguration.java
  clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/health/DockerRegistryHealthIndicatorTest.java
  clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsLifecycleHandlerTest.java
Labels: ready to merge

#5597 Use spinnaker http exception for 404
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProvider.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/userdata/LocalFileUserDataProviderSpec.groovy
  clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
  clouddriver-elasticsearch/src/main/java/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperation.java
  clouddriver-elasticsearch/src/test/groovy/com/netflix/spinnaker/clouddriver/elasticsearch/ops/DeleteEntityTagsAtomicOperationSpec.groovy
  gradle.properties
Labels: ready to merge

#5603 feat(artifacts/s3): improve error message/http response code when s3 …
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
  clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentialsTest.java
Labels: ready to merge
