Repository spinnaker/clouddriver, pull requests merged in 2021-11, with the labels that each got.

#5541 fix(lambda): remove parallel streams to improve performance
  clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgent.java
  clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaService.java
Labels: ready to merge, auto merged

#5564 fix(cloudfoundry): Avoid NPE when no instances are present.
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/cache/CacheRepositoryTest.java
Labels: ready to merge, auto merged

#5567 fix(cloudfoundry): add timeout to converter
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverterTest.java
Labels: ready to merge

#5572 fix(cloudfoundry): add test for non-empty fields
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Process.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/ProcessTest.java
Labels: ready to merge

#5570 fix(cloudfoundry): ensure process health is built
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/Processes.java
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/Process.java
  clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperation.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/ProcessesTest.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/model/v3/ProcessTest.java
  clouddriver-cloudfoundry/src/test/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/ops/DeployCloudFoundryServerGroupAtomicOperationTest.java
Labels: ready to merge, auto merged, backport-candidate

#5574 feat(security): Add codeql scanning for the project
  .github/workflows/codeql-analysis.yml
Labels: ready to merge, auto merged

#5576 fix(artifacts): close leaking input stream when downloading artifacts
  clouddriver-web/src/main/java/com/netflix/spinnaker/clouddriver/controllers/ArtifactController.java
Labels: ready to merge

#5580 chore(dependencies): use kork's version of testcontainers
  clouddriver-elasticsearch/clouddriver-elasticsearch.gradle
Labels: ready to merge

#5581 S3 artifact validation
  clouddriver-artifacts/clouddriver-artifacts.gradle
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/ArtifactCredentials.java
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactConfiguration.java
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentials.java
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactValidator.java
  clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/s3/S3ArtifactCredentialsTest.java
Labels: ready to merge, auto merged

#5585 fix(titus): Removing reference to bintray repo
  clouddriver-titus/clouddriver-titus.gradle
Labels: ready to merge

#5583 chore(meta): Remove myself from default reviewers
  CODEOWNERS
Labels: ready to merge, auto merged
