Repository spinnaker/clouddriver, pull requests merged in 2021-09, with the labels that each got.

#5500 feat(aws): enable custom property binding capability for aws accounts
  clouddriver-aws/clouddriver-aws.gradle
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCustomBinderConfiguration.java
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/CustomAccountsConfigurationProvider.java
Labels: ready to merge, sig/aws

#5505 feat(artifacts): support tokenFile for GitRepoArtifactCredentials and reload auth headers
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/config/BaseHttpArtifactCredentials.java
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitJobExecutor.java
  clouddriver-artifacts/src/main/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccount.java
  clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/gitRepo/GitRepoArtifactAccountTest.java
  clouddriver-artifacts/src/test/java/com/netflix/spinnaker/clouddriver/artifacts/github/GithubArtifactCredentialsTest.java
Labels: ready to merge

#5510 feat(provider/azure): Use v2-sku for Application Gateways
  clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/model/AzureAppGatewayDescription.groovy
  clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/ops/UpsertAzureAppGatewayAtomicOperation.groovy
  clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/templates/AzureAppGatewayResourceTemplate.groovy
  clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/converters/UpsertAzureAppGatewayAtomicOperationConverterSpec.groovy
  clouddriver-azure/src/test/groovy/com/netflix/spinnaker/clouddriver/azure/resources/appgateway/deploy/template/AzureAppGatewayResourceTemplateSpec.groovy
Labels: ready to merge, auto merged

#5482 Caching amis with the same name
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgent.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/controllers/AmazonNamedImageLookupControllerSpec.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/data/KeysSpec.groovy
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/ImageCachingAgentSpec.groovy
Labels: ready to merge, auto merged, backport-candidate, sig/aws

#5486 Load balancer instance health caching
  clouddriver-aws/clouddriver-aws.gradle
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgent.groovy
  clouddriver-aws/src/test/java/com/netflix/spinnaker/clouddriver/aws/provider/agent/AmazonLoadBalancerInstanceStateCachingAgentTest.java
Labels: ready to merge, auto merged, backport-candidate, sig/aws

#5481 Sql caching duplicates
  cats/cats-core/src/test/groovy/com/netflix/spinnaker/cats/mem/InMemoryCacheSpec.groovy
  cats/cats-redis/src/test/groovy/com/netflix/spinnaker/cats/redis/cache/RedisCacheSpec.groovy
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SpectatorSqlCacheMetrics.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCache.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cache/SqlCacheMetrics.kt
  cats/cats-sql/src/test/groovy/com/netflix/spinnaker/cats/sql/SqlCacheSpec.groovy
  cats/cats-test/src/main/groovy/com/netflix/spinnaker/cats/cache/CacheSpec.groovy
Labels: ready to merge, auto merged, backport-candidate

#5184 fix(kubernetes): update kubernetes jobStatus with relevant failure details
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatus.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProvider.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/model/KubernetesJobStatusTest.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/KubernetesJobProviderTest.java
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/model/base.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/model/failed-job-init-container-error.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/model/failed-job.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/model/runjob-deadline-exceeded.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/model/successful-job.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/base-with-completions.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/failed-job.yml
  clouddriver-kubernetes/src/test/resources/com/netflix/spinnaker/clouddriver/kubernetes/provider/view/runjob-deadline-exceeded.yml
Labels: ready to merge, auto merged, sig/kubernetes

#5509 fix(provider/azure): Fix isServerGroupDisabled for app gateway
  clouddriver-azure/src/main/groovy/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupAtomicOperation.groovy
Labels: ready to merge, auto merged

#5519 fix(provider/azure): Create RG if no load balancer
  clouddriver-azure/src/main/java/com/netflix/spinnaker/clouddriver/azure/resources/servergroup/ops/CreateAzureServerGroupWithoutLoadBalancersAtomicOperation.groovy
Labels: ready to merge, auto merged

#5512 refactor(cats/sql): made sharding configuration consistent
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/cats/sql/cluster/SqlCachingPodsObserver.kt
  cats/cats-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlShardingFilterConfiguration.kt
Labels: ready to merge, auto merged

#5518 fix(clouddriver-lambda): flakey test
  clouddriver-lambda/src/test/java/com/netflix/spinnaker/clouddriver/lambda/provider/agent/LambdaCachingAgentTest.java
Labels: ready to merge, auto merged

#5513 fix(kubernetes/artifacts): Support for legacy Clouddriver's artifact replacement logic
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacer.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHandler.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ArtifactReplacerTest.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/ReplacerTest.java
Labels: ready to merge, auto merged

#5528 feat(k8s): provide an option to turn off account health check for k8s accounts
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicator.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesConfiguration.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/health/KubernetesHealthIndicatorTest.java
Labels: ready to merge, auto merged

#5515 feat(k8s): provide an option to bypass getting namespaces when adding new k8s accounts
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/config/KubernetesConfigurationProperties.java
  clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsLifecycleHandler.java
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/security/KubernetesCredentialsLifecycleHandlerTest.java
Labels: ready to merge, auto merged

#5533 fix(lambda): add account and region to cache data
  clouddriver-lambda/src/main/java/com/netflix/spinnaker/clouddriver/lambda/service/LambdaService.java
Labels: ready to merge, backport-candidate

#5201 fix(core): Fix job executor stuck indefinitely
  clouddriver-core/src/main/java/com/netflix/spinnaker/clouddriver/jobs/local/JobExecutorLocal.java
Labels: ready to merge

#5539 feat(aws): provide a configurable option to parse aws accounts in a multi-threaded fashion
  clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoader.java
  clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java
  clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy
Labels: ready to merge

#5542 test(kubernetes/delete): add test coverage for deleting crd and custo…
  clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/description/GlobalResourcePropertyRegistrySpec.groovy
  clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/KubernetesDeleteManifestOperationTest.java
Labels: ready to merge

#5544 chore(clouddriver-sql): add missing com.fasterxml.jackson.datatype:ja…
  clouddriver-sql/clouddriver-sql.gradle
Labels: ready to merge

#5546 fix(aws/accounts): add @ConditionalOnMissingBean annotation for the default AccountsConfiguration bean so that it gets created only when no such bean exists
  clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonCredentialsInitializer.groovy
Labels: ready to merge

#5532 feat(aws): cache regions when parsing aws accounts
  clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/AmazonCredentialsParser.java
  clouddriver-aws/src/main/java/com/netflix/spinnaker/clouddriver/aws/security/config/CredentialsConfig.java
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy
Labels: ready to merge, auto merged

#5550 test(aws): fix flaky test
  clouddriver-aws/src/test/groovy/com/netflix/spinnaker/clouddriver/aws/security/AmazonBasicCredentialsLoaderSpec.groovy
Labels: ready to merge
